package lab7.server;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import lab7.collectionItems.*;
import lab7.utils.Config;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.*;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class DataBaseManager {

    private final HikariDataSource dataSource;
    private final Logger logger = LoggerFactory.getLogger(DataBaseManager.class);

    public DataBaseManager(String url, String username, String password) {
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl(url);
        config.setUsername(username);
        config.setPassword(password);

        config.setMaximumPoolSize(10);
        config.setConnectionTimeout(30000);
        config.setAutoCommit(true);

        this.dataSource = new HikariDataSource(config);
        logger.info("Пул соединений HikariCP успешно инициализирован.");

        initialize();
    }

    private static DataBaseManager instance = null;
    public static DataBaseManager getInstance(){
        if (instance == null)
            instance = new DataBaseManager(Config.getInstance().getDBURL(),
                    Config.getInstance().getDBUser(),
                    Config.getInstance().getDBPassword());
        return instance;
    }

    private void initialize() {
        String createUsersTable = """
            CREATE TABLE IF NOT EXISTS users (
                id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name     VARCHAR(100) UNIQUE NOT NULL,
                password VARCHAR(100) NOT NULL
            );
            """;

        String createSpaceMarinesTable = """
            CREATE TABLE IF NOT EXISTS space_marines (
                id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name           VARCHAR(255) NOT NULL,
                coord_x        BIGINT       NOT NULL,
                coord_y        BIGINT       NOT NULL,
                creation_date  DATE         NOT NULL,
                health         DOUBLE PRECISION NOT NULL,
                category       VARCHAR(50),
                weapon_type    VARCHAR(50)  NOT NULL,
                melee_weapon   VARCHAR(50),
                chapter_name           VARCHAR(255) NOT NULL,
                chapter_parent_legion  VARCHAR(255),
                chapter_marines_count  INTEGER,
                owner          VARCHAR(100) NOT NULL,
                ordernum       INTEGER      NOT NULL,
                CONSTRAINT fk_owner FOREIGN KEY (owner) REFERENCES users(name) ON DELETE CASCADE
            );
            """;

        update(createUsersTable);
        update(createSpaceMarinesTable);
        logger.info("Таблицы БД успешно инициализированы.");
    }

    public List<Map<String, Object>> select(String sql, Object... params) {
        List<Map<String, Object>> result = new ArrayList<>();

        try (Connection connection = dataSource.getConnection();
             PreparedStatement ps = connection.prepareStatement(sql)) {

            setParameters(ps, params);

            try (ResultSet rs = ps.executeQuery()) {
                ResultSetMetaData metaData = rs.getMetaData();
                int columnCount = metaData.getColumnCount();

                while (rs.next()) {
                    Map<String, Object> row = new LinkedHashMap<>();
                    for (int i = 1; i <= columnCount; i++) {
                        row.put(metaData.getColumnName(i), rs.getObject(i));
                    }
                    result.add(row);
                }
            }
        } catch (SQLException e) {
            logger.error("Ошибка SELECT: {}", e.getMessage());
        }
        return result;
    }

    public int update(String sql, Object... params) {
        try (Connection connection = dataSource.getConnection();
             PreparedStatement ps = connection.prepareStatement(sql)) {

            setParameters(ps, params);
            return ps.executeUpdate();

        } catch (SQLException e) {
            logger.error("Ошибка UPDATE/INSERT/DELETE: {}", e.getMessage());
            return -1;
        }
    }

    private void setParameters(PreparedStatement ps, Object... params) throws SQLException {
        if (params != null) {
            for (int i = 0; i < params.length; i++) {
                ps.setObject(i + 1, params[i]);
            }
        }
    }

    /**
     * Загрузить все записи из таблицы space_marines, упорядоченные по ordernum.
     */
    public List<SpaceMarine> loadAllSpaceMarines() {
        List<SpaceMarine> result = new ArrayList<>();
        String sql = """
            SELECT id, name, coord_x, coord_y, creation_date, health,
                   category, weapon_type, melee_weapon,
                   chapter_name, chapter_parent_legion, chapter_marines_count,
                   owner, ordernum
            FROM space_marines
            ORDER BY ordernum
            """;

        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                int id = rs.getInt("id");
                String name = rs.getString("name");
                long coordX = rs.getLong("coord_x");
                long coordY = rs.getLong("coord_y");
                LocalDate creationDate = rs.getDate("creation_date").toLocalDate();
                double health = rs.getDouble("health");

                String categoryStr = rs.getString("category");
                AstartesCategory category = categoryStr != null
                        ? AstartesCategory.valueOf(categoryStr) : null;

                Weapon weaponType = Weapon.valueOf(rs.getString("weapon_type"));

                String meleeStr = rs.getString("melee_weapon");
                MeleeWeapon meleeWeapon = meleeStr != null
                        ? MeleeWeapon.valueOf(meleeStr) : null;

                String chapterName = rs.getString("chapter_name");
                String chapterParentLegion = rs.getString("chapter_parent_legion");
                Integer chapterMarinesCount = (Integer) rs.getObject("chapter_marines_count");

                String owner = rs.getString("owner");

                Coordinates coordinates = new Coordinates(coordX, coordY);
                Chapter chapter = new Chapter(chapterName, chapterParentLegion, chapterMarinesCount);

                SpaceMarine marine = new SpaceMarine(id, name, coordinates, creationDate,
                        health, category, weaponType, meleeWeapon, chapter, owner);
                result.add(marine);
            }
            logger.info("Загружено {} записей из БД.", result.size());
        } catch (SQLException e) {
            logger.error("Ошибка загрузки коллекции из БД: {}", e.getMessage());
        }
        return result;
    }

    /**
     * Вставить SpaceMarine в БД с указанным ordernum и owner.
     * @return true, если вставка успешна.
     */
    public boolean insertSpaceMarine(SpaceMarine marine, int ordernum) {
        String sql = """
            INSERT INTO space_marines
                (id, name, coord_x, coord_y, creation_date, health,
                 category, weapon_type, melee_weapon,
                 chapter_name, chapter_parent_legion, chapter_marines_count,
                 owner, ordernum)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """;

        int rows = update(sql,
                marine.getID(),
                marine.getName(),
                marine.getCoordinates().getX(),
                marine.getCoordinates().getY(),
                marine.getCreationDate(),
                marine.getHealth(),
                marine.getCategory() != null ? marine.getCategory().name() : null,
                marine.getWeaponType().name(),
                marine.getMeleeWeapon() != null ? marine.getMeleeWeapon().name() : null,
                marine.getChapter().getName(),
                marine.getChapter().getParentLegion(),
                marine.getChapter().getMarinesCount(),
                marine.getOwner(),
                ordernum
        );

        if (rows > 0) {
            logger.info("SpaceMarine id={} (owner={}) добавлен в БД.", marine.getID(), marine.getOwner());
            return true;
        }
        logger.error("Не удалось добавить SpaceMarine id={} в БД.", marine.getID());
        return false;
    }

    /**
     * Обновить все поля SpaceMarine в БД по id.
     * Owner не изменяется — проверка прав выполняется на уровне CollectionController.
     * @return true, если обновлена хотя бы одна строка.
     */
    public boolean updateSpaceMarine(SpaceMarine marine) {
        String sql = """
            UPDATE space_marines SET
                name = ?, coord_x = ?, coord_y = ?, creation_date = ?, health = ?,
                category = ?, weapon_type = ?, melee_weapon = ?,
                chapter_name = ?, chapter_parent_legion = ?, chapter_marines_count = ?
            WHERE id = ? AND owner = ?
            """;

        int rows = update(sql,
                marine.getName(),
                marine.getCoordinates().getX(),
                marine.getCoordinates().getY(),
                marine.getCreationDate(),
                marine.getHealth(),
                marine.getCategory() != null ? marine.getCategory().name() : null,
                marine.getWeaponType().name(),
                marine.getMeleeWeapon() != null ? marine.getMeleeWeapon().name() : null,
                marine.getChapter().getName(),
                marine.getChapter().getParentLegion(),
                marine.getChapter().getMarinesCount(),
                marine.getID(),
                marine.getOwner()
        );

        if (rows > 0) {
            logger.info("SpaceMarine id={} обновлён в БД.", marine.getID());
            return true;
        }
        logger.error("Не удалось обновить SpaceMarine id={} в БД (возможно, не хозяин).", marine.getID());
        return false;
    }

    /**
     * Удалить SpaceMarine по id, только если переданный owner совпадает с владельцем.
     * @return true, если удалена хотя бы одна строка.
     */
    public boolean deleteSpaceMarineById(int id, String owner) {
        String sql = "DELETE FROM space_marines WHERE id = ? AND owner = ?";
        int rows = update(sql, id, owner);
        if (rows > 0) {
            logger.info("SpaceMarine id={} удалён из БД (owner={}).", id, owner);
            return true;
        }
        logger.error("Не удалось удалить SpaceMarine id={} из БД (возможно, не хозяин).", id);
        return false;
    }

    /**
     * Удалить SpaceMarine с максимальным ordernum, только если owner совпадает.
     * @return id удалённого элемента, или -1 при ошибке.
     */
    public int deleteLastSpaceMarine(String owner) {
        String sql = """
            DELETE FROM space_marines
            WHERE id = (
                SELECT id FROM space_marines WHERE owner = ? ORDER BY ordernum DESC LIMIT 1
            )
            RETURNING id
            """;

        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, owner);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    int deletedId = rs.getInt("id");
                    logger.info("Последний SpaceMarine id={} (owner={}) удалён из БД.", deletedId, owner);
                    return deletedId;
                }
            }
        } catch (SQLException e) {
            logger.error("Ошибка при удалении последнего элемента: {}", e.getMessage());
        }
        return -1;
    }

    /**
     * Удалить все SpaceMarine данного owner с id > переданного значения.
     * @return количество удалённых строк, или -1 при ошибке.
     */
    public int deleteSpaceMarinesWithIdGreaterThan(int id, String owner) {
        String sql = "DELETE FROM space_marines WHERE id > ? AND owner = ?";
        int rows = update(sql, id, owner);
        if (rows >= 0) {
            logger.info("Удалено {} элементов с id > {} (owner={}) из БД.", rows, id, owner);
        } else {
            logger.error("Ошибка при удалении элементов с id > {}.", id);
        }
        return rows;
    }

    /**
     * Удалить все записи space_marines, принадлежащие указанному owner.
     * @return количество удалённых строк, или -1 при ошибке.
     */
    public int deleteSpaceMarinesByOwner(String owner) {
        String sql = "DELETE FROM space_marines WHERE owner = ?";
        int rows = update(sql, owner);
        if (rows >= 0) {
            logger.info("Удалено {} записей owner={} из БД.", rows, owner);
        } else {
            logger.error("Ошибка при удалении записей owner={}.", owner);
        }
        return rows;
    }

    /**
     * Удалить все записи из space_marines (полная очистка).
     * @return количество удалённых строк, или -1 при ошибке.
     */
    public int deleteAllSpaceMarines() {
        String sql = "DELETE FROM space_marines";
        int rows = update(sql);
        if (rows >= 0) {
            logger.info("Все записи удалены из БД ({} строк).", rows);
        } else {
            logger.error("Ошибка при удалении всех записей.");
        }
        return rows;
    }

    /**
     * Сдвинуть ordernum всех записей, у которых ordernum >= переданного, на +1.
     * @return количество обновлённых строк, или -1 при ошибке.
     */
    public int shiftOrdernumsUpFrom(int fromOrdernum) {
        String sql = "UPDATE space_marines SET ordernum = ordernum + 1 WHERE ordernum >= ?";
        int rows = update(sql, fromOrdernum);
        if (rows >= 0) {
            logger.info("Сдвинуты ordernum для {} записей (>= {}).", rows, fromOrdernum);
        } else {
            logger.error("Ошибка при сдвиге ordernum.");
        }
        return rows;
    }

    /**
     * Получить максимальный id среди SpaceMarine в БД.
     */
    public int getMaxSpaceMarineId() {
        String sql = "SELECT COALESCE(MAX(id), 0) AS max_id FROM space_marines";
        List<Map<String, Object>> rows = select(sql);
        if (!rows.isEmpty()) {
            return ((Number) rows.get(0).get("max_id")).intValue();
        }
        return 0;
    }

    /**
     * Получить максимальный ordernum среди SpaceMarine в БД.
     */
    public int getMaxOrdernum() {
        String sql = "SELECT COALESCE(MAX(ordernum), -1) AS max_ord FROM space_marines";
        List<Map<String, Object>> rows = select(sql);
        if (!rows.isEmpty()) {
            return ((Number) rows.get(0).get("max_ord")).intValue();
        }
        return -1;
    }

    /**
     * Сбросить последовательность space_marines_id_seq до текущего максимума id.
     */
    public void syncIdSequence() {
        String sql = "SELECT setval('space_marines_id_seq', (SELECT COALESCE(MAX(id), 1) FROM space_marines))";
        update(sql);
    }

    public void close() {
        if (dataSource != null && !dataSource.isClosed()) {
            dataSource.close();
            logger.info("Пул соединений закрыт.");
        }
    }

    public boolean createUser(String login, String password){
        String sql = """
            INSERT INTO users
                (name, password)
            VALUES (?, ?)
            """;
        int rows = update(sql,
                login,
                password
        );

        if (rows > 0) {
            logger.info("user login={} добавлен в БД.", login);
            return true;
        }
        logger.error("Не удалось добавить user login={} в БД.", login);
        return false;
    }

//    public boolean hasUser(String login, String password){
//        System.out.println("has user start");
//        String sql = """
//                SELECT * FROM users
//                WHERE name=? and password=?
//                """;
//        try (PreparedStatement ps = dataSource.getConnection().prepareStatement(sql)) {
//            setParameters(ps, login, password);
//
//            ResultSet set = ps.executeQuery();
//            return set.next();
//        } catch (SQLException e) {
//            throw new RuntimeException(e);
//        }
//
//        //return false;
//    }

    public String getUserPasswordHash(String login){
        String sql = """
                SELECT password FROM users
                WHERE name=?
                """;
        try (Connection connection = dataSource.getConnection();
             PreparedStatement ps = connection.prepareStatement(sql)) {
            //System.out.println(login);
            setParameters(ps, login);

            ResultSet set = ps.executeQuery();
            if (set.next()) return set.getString(1);
            else            return null;
        } catch (SQLException e) {
            e.printStackTrace();
            return null;
            //throw new RuntimeException(e);
        }
    }

    public String getOwnerNameById(int id){
        String sql = """
                SELECT owner FROM space_marines
                WHERE id=?
                """;
        try (Connection connection = dataSource.getConnection();
             PreparedStatement ps = connection.prepareStatement(sql)) {
            setParameters(ps, id);

            ResultSet set = ps.executeQuery();
            if (set.next()) return set.getString(1);
            else            return null;
        } catch (SQLException e) {
            e.printStackTrace();
            return null;
            //throw new RuntimeException(e);
        }
    }

    public boolean hasUser(String login){
        //System.out.println("has user start");
        String sql = """
                SELECT * FROM users
                WHERE name=?
                """;
        try (Connection connection = dataSource.getConnection();
             PreparedStatement ps = connection.prepareStatement(sql)) {
            setParameters(ps, login);

            ResultSet set = ps.executeQuery();
            return set.next();
        } catch (SQLException e) {
            return false;
            //throw new RuntimeException(e);
        }
    }


}
